# netlify.toml — Quasar SPA deploy

[build]
  command = "npm run build"        # runs: quasar build -m spa
  publish = "dist/spa"             # Quasar SPA output

  # (optional but recommended) Use a modern Node version on Netlify
  environment = { NODE_VERSION = "20" }

# Single Page App routing: send all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (optional) Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# (optional) Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
